### ISSUE TITLE
Asking for condition Mesmerized but this is jot a base game condition

### ISSUE THREAD

**Issue by powerjeremy** [antontimmermans/MOMDATD#17]
After the starspawn arrived i was asked to do an influence check at one point. If i failed i was to become Mesmerized. I think this is a condition from Beyond the Threshold expansion but this expansion isnt listed as a requirement. I had only selected the base game in the COLLECTION section of the valkyrie app.

**Comment by antontimmermans** [comment]
This may be a valkyrie bug since the scenario does not 'mesmerize'  in any event. I will open a ticket in Valkyrie app repository and link it to this ticket.
Well spotted, thanks for reporting.

**Comment by BenRQ** [comment]
Hi @powerjeremy , when did you play this game ?
Did you posted a rating and comments at the end of the game?

**Comment by antontimmermans** [comment]
@BenRQ Rating and comments posted entry of play can be found in LiveStats google doc. Entry recorded at: 3/19/2019 3:56:07

**Comment by BenRQ** [comment]
OK thanks

**Comment by powerjeremy** [comment]
Yeah i was asking on bgg about how to rate the scenarios and read the other reviews. I didnt realise you had to finish the scenario first.

I tried to leave descriptive comments rather than "it was good! I liked it!" Lol this was the first scenario i played and it was pretty cool. The valkyrie app is pretty nice too. Looking forward to playing the other ones. Hopefully one day ill make my own.

**Comment by antontimmermans** [comment]
@powerjeremy I really appreciate it a lot that you made such nice detailed feedback in this ticket and all other tickets you wrote on this scenario. Thank you very much!

**Comment by powerjeremy** [comment]
Glad to help. I noticed spelling mistakes in some parts. I didnt keep track of them (there were only a small number). I could help edit and correct mistakes if you had a document or script or something.

**Comment by antontimmermans** [comment]
@powerjeremy the displayed texts are all collected in the localization.english file. It is directly downloadable from this repository. Your improvement suggestions are welcome:  
https://github.com/antontimmermans/MOMDATD/blob/master/Localization.English.txt

**Comment by powerjeremy** [comment]
Hey. Sorry im not sure what this is... Is this so you can read through and
edit grammar and spelling?  How would i make changes?

**Comment by antontimmermans** [comment]
This file contains all texts that are used in the scenario.  It looks complicated at first but it's easy enough once you know what you are looking at.
Every line references to a button, event  or some other feature in the scenario. The reference part is everything infront of the first comma. 

For example:
`EventStreet2PlaceTile.text,On the east side of the town square you find the street that leads to a small park. Place the {c:TileStreet2} as indicated.`

-> `EventStreet2PlaceTile.text,` 
    is the part that references to the event that is called when placing the street 2 tile. This is the technical part you can ignore for spelling.
-> `On the east side of the town square you find the street that leads to a small park. Place the {c:TileStreet2} as indicated.`
   is the text that will be displayed and should gramatically be correct. The {c:TileStreet2} display the correct name of the tile as it is used in the game.

other weird characters are jsut formatting characters that you can ignore, fore example:
`"{action} <i>""Can you hear that sound?""</i>"`
will display the action symbol and the text _"Can you hear that sound?"_ in italics

The files may be editable with programs like MSWord, but may not tbe saved by that program because all kind of invisible formatting codes will be added in the file, which will crash Valkyrie. That is why they better can be eddited with (freeware) like Atom or Notepad++.

Zaalock is translating my Chapeldown Manor scenario to Polish and he does it by importing it in a google doc spreadsheet. I guess he wrote some import/export macro's to deal with that.

I realize that it looks scary at first, but you will get used to it :)

if you go to https://github.com/antontimmermans/MOMDATD you will see a green clone or download button:
![image](https://user-images.githubusercontent.com/42072372/55034812-b18fba80-5016-11e9-8f79-2f50d1b15e4b.png)

if you click it you will get a local copy and you can edit the file with one of the programs that I suggested. When  you are done, you can attach your version of the localization file to this ticket. and i will merge it back into the scenario.

**Comment by powerjeremy** [comment]
Ok ill give it a try and see what i can do.

**Comment by antontimmermans** [comment]
@powerjeremy i just saw that Scrubbles made a Very nice update in the tutorial in how to modify (or translate) the texts for scenario's.  https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit

Its on page 184

**Comment by antontimmermans** [comment]
Not a scenario bug (see also linked Ticket in Valkyrie
