### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by zcaalock** [antontimmermans/MOMDATD#18]
Hi, i`ve started polish translation. If anyone want to contribute here is the link:

https://docs.google.com/spreadsheets/d/1scjTWt49P39-fz56tx0vby_DXoEksKOTDV-eRqgYRSo/edit?usp=sharing

**Comment by chrismaliszewski** [comment]
@zcaalock, I have a question. Lines 56 onwards, dialogue with the kid. 

Do you purposely don't use **ę** and other Polish letters in the dialogue when the kid speaks? I want to be sure that it isn't a mistake. It's not a problem if you say "yes". 

Could you also say why you decided to do that? In the English version, the kid speaks normally, w/o any accent except 'ear & 'im from 59 but it's something else than a childish way of talking but rather "arrr"/pirate/people leaving on a shore way of saying from what I know.

**Comment by chrismaliszewski** [comment]
@antontimmermans, again, I'll write my comments regarding the English version. I'll be extending the list.
109: You introduce the boy twice, in two sentences in a row:  "you see a little boy" ... "This is the sad little boy.". I'm also not sure why you use "the boy" in the second sentence as if a player should already know the boy from somewhere else while he/she has just only met him in the previous sentence; there isn't any other time the boy is mentioned in the scenario, at least from what I checked.
**My suggestion:** On the street you see a little sad boy leaning casually against the back of the warehouse. Place the Orange Person Token as indicated.
209: the similar problem of introducing a character for the second time. 
284: wrong usage of the "amount" word. It should be "number". Grammarly made the suggestion, not me. Also, there is a misspelling of "whish". 
300: 
1. "there where" -> "there were". 
2. The whole sentence "But don't be puttin all off them that cursed bell during the autumn" if off. I spoke with a Canadian girl and she was not able to understand it by any mean. First of all, do + be + ing, second, put + sth + off has a different meaning than what you want to say, third, there are other problems. 

**Our suggestion:** But don't take them off of that cursed bell during the autumn.
301: this one is also unclear. Also, "top off" ->"top of"
303: "them neat" -> "the neat"
328: delete "This is the harbormaster.". We already know who he is. OR change it to something like "it's the true form of the harbormaster."
338: "a some"
365: a quote " is missing
374: misspelling in "suprised" -> surprised
372 & 373: there is (not) "s" in the sentence :).
387: instead of "behind and call him" I'd write "behind so you call him". The original sentence doesn't sound right to me; it isn't bad but could be better. Google also has a problem with translating the sentence and that's why I took a look on this sentence.
426: 
1. "...the harbormaster looks up **and** you and grunts" -> **at**
2. "with a weak smile" -> I didn't know that phrase :). FYI, I also found this: "thin smile" (https://www.merriam-webster.com/dictionary/thin%20smile).

429: "bend the demons will to mine" -> demons' (possessive)
431: "I don not think" -> "do not"
445: "Someone has been **practicing**..." -> practising
457: intestants -> intestines
459: from near the harbormasters office -> from near the harbormaster's office
469: lamp light -> lamplight
499: where -> were
518: "Something big and evil is attracted by this sound and moving closer" -> I'd add "**is** moving closer" as there is no verb in the dependent clause.
524: I have no idea what this sentence is about. I'll be a little exaggerating: what is dragging what; the background tugs the mind or the sound the mind?; is the sound hearable in the background or at your mind? 
567 & 570 & 582: "monsters tentacles" -> lack of possessive
613: **Which monster is Big Bad???** I don't recognise the name. 
618: "You notice a little piece of paper label with a piece of blue string attached to it.", too many pieces :)
My suggestion: You notice a little piece of paper with a blue string attached to it.
629: "half burned" -> half-burned
630: Bell setting/configuration -> Bell's [...]
633: "half opened" -> half-opened 
684: gardener -> a gardener

**Comment by chrismaliszewski** [comment]
@antontimmermans, a question about 297, 299 & 305. By saying "bugged" you mean "the game is messed up/a player is in a sh**hole and must restart the game" or you had something else on your mind? When does this kind of event appear to a player?

**Comment by zcaalock** [comment]
"ware'ouse some minutes later. Him thought nobody saw 'im, but I dids" this looks like accent to me.
Maeby we should stick to normal language, its hard to reproduce it in polish

**Comment by chrismaliszewski** [comment]
Yeah, ok, the kid has an accent but, as I said, it's rather an accent of "people leaving on a shore way of saying" while omitting ę/ł etc. in Polish seems rather a childish way of speaking rather than an accent. 

Do you remember scrumbles' scenario in the madhouse? There was a guy speaking in a similar manner. It was easier to translate it when a character is an adult because you can add words which are inappropriate to a child creating something between a dialect and "bad-way-of-speaking" using vulgarisms. 

Agreed with the last bit. In Polish, we don't have this kind of dialect and it'll be better to stay with "sim-Plish"/simple Polish :).

**Comment by antontimmermans** [comment]
> @antontimmermans, a question about 297, 299 & 305. By saying "bugged" you mean "the game is messed up/a player is in a sh**hole and must restart the game" or you had something else on your mind? When does this kind of event appear to a player?

@chrismaliszewski This message should never appear to a player. I have used the message during debugging and testing of the scenario. you can either skip the translation or write something funny :)

**Comment by antontimmermans** [comment]
> Yeah, ok, the kid has an accent but, as I said, it's rather an accent of "people leaving on a shore way of saying" while omitting ę/ł etc. in Polish seems rather a childish way of speaking rather than an accent.
> 
> Do you remember scrumbles' scenario in the madhouse? There was a guy speaking in a similar manner. It was easier to translate it when a character is an adult because you can add words which are inappropriate to a child creating something between a dialect and "bad-way-of-speaking" using vulgarisms.
> 
> Agreed with the last bit. In Polish, we don't have this kind of dialect and it'll be better to stay with "sim-Plish"/simple Polish :).

@zcaalock @chrismaliszewski I assume that when small children in polish learn to speak they sometimes get it "almost right". Example: He is hungry and I am hungry --> He is hungry and me is hungry.
The idea is to make the boy sound streetwise but with hardly any proper education. It would be nice if you could make the text 'childish' that way.

**Comment by antontimmermans** [comment]
@chrismaliszewski i know that zcaalock is somtimes on the valkyrie writers channel on Discord, but are you too? https://discord.gg/Wz5KQF

**Comment by chrismaliszewski** [comment]
Polish lesson :): the Polish language doesn't work like that. 
In our language, kids mostly mispronounce some words or letters rather than use the wrong grammar form. I.e. many kids have problems with:
1. (I think it's a problem in many languages, not only Polish) pronouncing "r"; imaging saying "light" instead of "right",
2. properly pronouncing ą,ę letters in words by changing their form to on/om and e; [correct pronunciation of the letters](https://www.youtube.com/watch?v=L_HUKdjfDTY).  Even Google Translate has problems with pronouncing ę: [link](https://translate.google.pl/#view=home&op=translate&sl=pl&tl=en&text=%C4%85%20on%20om%20%0A%C4%99%20e)
3. many more cases, ł -> l, sz -> s, b -> p, etc.

Grammar is even worse... It's a book-size topic...

That's why @zcaalock wrote "... **slysysz**? ... **słysze** ... **glośniej**" instead of "słyszysz", "słyszę" & głośniej" which simulates the way a child could/would talk.

**Comment by chrismaliszewski** [comment]
> @chrismaliszewski i know that zcaalock is somtimes on the valkyrie writers channel on Discord, but are you too? https://discord.gg/Wz5KQF

I'm not. I've never used Discord. Who knows, maybe I'll start some day.

**Comment by chrismaliszewski** [comment]
@antontimmermans, the English check is done. Line 613 requires your help. What is Big Bad? I don't recognise this one. From the name of the even I presume it's a test event, right? I'd to be certain. 

@zcaalock, could you please check the rest of the notes I left and correct the text if needed :).

**Comment by antontimmermans** [comment]
> @antontimmermans, the English check is done. Line 613 requires your help. What is Big Bad? I don't recognise this one. From the name of the even I presume it's a test event, right? I'd to be certain.
> 
@chrismaliszewski line 613 is text for a test button, it was used to test what will happen if the final big demon is spawned. There is no need to translate this text. In normal play this will never show.

BTW i think you will like the discord channel. the Valkyrie app builders are there, scenario writers are and also scenario translaters.

**Comment by zcaalock** [comment]
@chrismaliszewski done. You can find all Polish translations for cards, tiles etc. in \Program Files (x86)\Valkyrie\valkyrie_Data\StreamingAssets\text and AppData\Roaming\Valkyrie\MoM\import\text

**Comment by chrismaliszewski** [comment]
@zcaalock, thanks. I also checked Polish instruction (http://galakta.pl/download/Posiad%C5%82osc_Szalenstwa_2_edycja_instrukcja.pdf) for other translations. 

I think I'm done with the translation. If you think it's done, you can publish it.

**Comment by antontimmermans** [comment]
@zcaalock @chrismaliszewski how's the translation going guys? You you have a translated localization.polish.txt file for me to integrate?

**Comment by zcaalock** [comment]
@antontimmermans sorry i forgot to compile the file, ill upload it here later today, need to edit some last things

**Comment by zcaalock** [comment]
[Localization.Polish.txt](https://github.com/antontimmermans/MOMDATD/files/3107978/Localization.Polish.txt)

done, you can upload the file

**Comment by zcaalock** [comment]
@chrismaliszewski mam wrażenie (chyba że się mylę i sam coś namieszałem), że w wielu miejscach w tym i poprzednim scenariuszu zmieniłeś "ci" na "tobie"
np. tu: "zdajesz sobie sprawę, że posiadłość płata **tobie** figle" to nie jest poprawna forma, powinno być "zdajesz sobie sprawę, że posiadłość płata **ci** figle". 
"tobie" używa się w potocznej mowie na podlasiu i wschodnich częściach Polski, dla reszty może to brzmieć dziwnie.

**Comment by chrismaliszewski** [comment]
Przyjęte. Szczerze powiedziawszy, nigdy nie zaglebialem się w różnicę ci/tobie do tego momentu, myśląc że są one zamienne.

Dla jasności, https://sjp.pwn.pl/poradnia/haslo/ci-czy-tobie;5696.html. 

Dzięki za zwrócenie uwagi. 
Zmieniłeś spolszczenie, zostawić je takie jakie jest teraz, czy uważasz że lepiej będzie jak je poprawię?

 
@antontimmermans, we discussing one eventual correction to the translation.

**Comment by antontimmermans** [comment]
> @antontimmermans, again, I'll write my comments regarding the English version. I'll be extending the list.
> 109: You introduce the boy twice, in two sentences in a row: "you see a little boy" ... "This is the sad little boy.". I'm also not sure why you use "the boy" in the second sentence as if a player should already know the boy from somewhere else while he/she has just only met him in the previous sentence; there isn't any other time the boy is mentioned in the scenario, at least from what I checked.
> **My suggestion:** On the street you see a little sad boy leaning casually against the back of the warehouse. Place the Orange Person Token as indicated.
> 209: the similar problem of introducing a character for the second time.
> 284: wrong usage of the "amount" word. It should be "number". Grammarly made the suggestion, not me. Also, there is a misspelling of "whish".
> 300:
> 
> 1. "there where" -> "there were".
> 2. The whole sentence "But don't be puttin all off them that cursed bell during the autumn" if off. I spoke with a Canadian girl and she was not able to understand it by any mean. First of all, do + be + ing, second, put + sth + off has a different meaning than what you want to say, third, there are other problems.
> 
> **Our suggestion:** But don't take them off of that cursed bell during the autumn.
> 301: this one is also unclear. Also, "top off" ->"top of"
> 303: "them neat" -> "the neat"
> 328: delete "This is the harbormaster.". We already know who he is. OR change it to something like "it's the true form of the harbormaster."
> 338: "a some"
> 365: a quote " is missing
> 374: misspelling in "suprised" -> surprised
> 372 & 373: there is (not) "s" in the sentence :).
> 387: instead of "behind and call him" I'd write "behind so you call him". The original sentence doesn't sound right to me; it isn't bad but could be better. Google also has a problem with translating the sentence and that's why I took a look on this sentence.
> 426:
> 
> 1. "...the harbormaster looks up **and** you and grunts" -> **at**
> 2. "with a weak smile" -> I didn't know that phrase :). FYI, I also found this: "thin smile" (https://www.merriam-webster.com/dictionary/thin%20smile).
> 
> 429: "bend the demons will to mine" -> demons' (possessive)
> 431: "I don not think" -> "do not"
> 445: "Someone has been **practicing**..." -> practising
> 457: intestants -> intestines
> 459: from near the harbormasters office -> from near the harbormaster's office
> 469: lamp light -> lamplight
> 499: where -> were
> 518: "Something big and evil is attracted by this sound and moving closer" -> I'd add "**is** moving closer" as there is no verb in the dependent clause.
> 524: I have no idea what this sentence is about. I'll be a little exaggerating: what is dragging what; the background tugs the mind or the sound the mind?; is the sound hearable in the background or at your mind?
> 567 & 570 & 582: "monsters tentacles" -> lack of possessive
> 613: **Which monster is Big Bad???** I don't recognise the name.
> 618: "You notice a little piece of paper label with a piece of blue string attached to it.", too many pieces :)
> My suggestion: You notice a little piece of paper with a blue string attached to it.
> 629: "half burned" -> half-burned
> 630: Bell setting/configuration -> Bell's [...]
> 633: "half opened" -> half-opened
> 684: gardener -> a gardener

@chrismaliszewski thanks for the english spelling and text improvement suggestions. It is clear that foreign languagues is not my stongest skill ;-)

**Comment by chrismaliszewski** [comment]
Sure, no problem. You're doing a great job!

English is neither my first language so I also make mistakes. To prevent
them from happening, I use a free tool called Grammarly. It has improved my
writing a lot since I started using it. It has plugins to Chrome and MS
Word.

**Comment by zcaalock** [comment]
@chrismaliszewski przejrzałem jeszcze raz cały tekst, poprawiłem kilka zdań i uważam, że teraz brzmią bardziej składnie i logicznie biorąc pod uwagę całość opowieści. Zauważyłem też kilka błędów składni i gramatycznych więc myślę, że poprawiony tekst będzie się nadawać.

@antontimmermans sorry for polish, we are discussing some polish related stuff. IMO the text is ready for publishing. BTW did you came up with the story by yourself or is it inspired from a book?

**Comment by zcaalock** [comment]
@chrismaliszewski masz jakiś pomysł na kolejne tłumaczenie? Te dwa ostatnie scenariusze były całkiem udane i na poziomie. Jeśli chodzi o "ryse na rzeczywistości" to bardzo ciężko się to tłumaczy bo to jest port z francuskiego i dziwnie te zdania są sformułowane. Może A Glimpse of the Past?

**Comment by antontimmermans** [comment]
@chrismaliszewski @zcaalock  If I may ask you one more favor on the matter of the Polish language:

I have created a new puzzle in a style that was used in the film Da Vinci code: a Cryptex. It is currently set up for 26 letters A-Z, empty space and a dash '-'. (in total 28 positions). The graphics and button positioning should work on any device/screen aspect and resolution.

The attached scenario is quite simple: it will display the Cyptexpuzzle and with the up/down arrows, you can spell a 5 letter word with it. When you press "Guess" you will see a pass or fail text depending on if you guessed it right. _Hint: code word for this sample is the fruit (in English) that hit Newtons' head which resulted in his theory of gravity. ;-)_
[Cryptex.zip](https://github.com/antontimmermans/MOMDATD/files/3113749/Cryptex.zip)

I was wondering if this would be usable at all in the Polish language.  Would it require more than 28 values per digit to deal with the polish alphabet?

**Comment by chrismaliszewski** [comment]
I created a new topic regarding the Cryptex so we can discuss the topic only.

**Comment by chrismaliszewski** [comment]
> @chrismaliszewski i know that zcaalock is somtimes on the valkyrie writers channel on Discord, but are you too? https://discord.gg/Wz5KQF

@antontimmermans, could you send me the invitation again as the one is invalid/expired?

**Comment by antontimmermans** [comment]
@chrismaliszewski https://discord.gg/yhtWDRw

**Comment by antontimmermans** [comment]
Closing this issue; translations and text improvements are integrated and released.
